[package]
name = "hellofetch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytesize = "1.3.0"
colored = "2.1.0"
sysinfo = "0.30.12"
